image: ruby:2.3

stages:
  - preview
  - publish

preview:
  stage: preview
  environment: preview
  only:
    - preview
  script:
    - make ci-install
    - make ci-version
    - make build
    - make preview

publish:
  stage: publish
  environment: publish
  only:
    - master
  script:
    - make ci-install
    - make ci-version
    - make build
    - make publish
